name = "dd-ingester"
main = "src/index.ts"
compatibility_date = "2025-03-26"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "SEEN_URLS"
id = "dfbf88ee16984601b5227d85902fe252"

[[d1_databases]]
binding = "DB"
database_name = "dd-ingester-db"
database_id = "c29a8ecd-5fef-4dcc-8f35-f557b06a7e33"

[[queues.producers]]
queue = "rss-articles"
binding = "RSS_QUEUE"

[[queues.producers]]
queue = "rss-articles-rendered"
binding = "RENDERED_QUEUE"

[[queues.producers]]
queue = "rss-articles-cleaned"
binding = "CLEANED_QUEUE"

[[queues.producers]]
queue = "rss-articles-incorporate"
binding = "INCORPORATE_QUEUE"

[[queues.consumers]]
queue = "rss-articles"
max_retries = 5
max_batch_size = 5
max_batch_timeout = 30

[[queues.consumers]]
queue = "rss-articles-rendered"
max_retries = 5
max_batch_size = 1
max_batch_timeout = 60
max_concurrency = 1

[[queues.consumers]]
queue = "rss-articles-cleaned"
max_retries = 5
max_batch_size = 1
max_batch_timeout = 60
max_concurrency = 1

[[r2_buckets]]
bucket_name = "dd-articles-markdown"
binding = "ARTICLES_BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "e0bc1f55dc6fc3f8fe870087199a2ee3"

[[services]]
binding = "MODEL_ROUTER"
service = "dd-model-router"

[observability]
enabled = true
